# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wCamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wCamera(object):
    def setupUi(self, wCamera):
        wCamera.setObjectName("wCamera")
        wCamera.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(wCamera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bMeasure = QtWidgets.QPushButton(wCamera)
        self.bMeasure.setObjectName("bMeasure")
        self.verticalLayout.addWidget(self.bMeasure)
        self.wPlot = PlotWidget(wCamera)
        self.wPlot.setObjectName("wPlot")
        self.verticalLayout.addWidget(self.wPlot)

        self.retranslateUi(wCamera)
        QtCore.QMetaObject.connectSlotsByName(wCamera)

    def retranslateUi(self, wCamera):
        _translate = QtCore.QCoreApplication.translate
        wCamera.setWindowTitle(_translate("wCamera", "Form"))
        self.bMeasure.setText(_translate("wCamera", "Measure"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wCamera = QtWidgets.QWidget()
    ui = Ui_wCamera()
    ui.setupUi(wCamera)
    wCamera.show()
    sys.exit(app.exec_())
